/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Upcloud.Client.SwaggerDateConverter;

namespace Upcloud.Model
{
    /// <summary>
    /// ServerLoginUserSshKeys
    /// </summary>
    [DataContract]
    public partial class ServerLoginUserSshKeys :  IEquatable<ServerLoginUserSshKeys>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServerLoginUserSshKeys" /> class.
        /// </summary>
        /// <param name="sshKey">sshKey.</param>
        public ServerLoginUserSshKeys(List<string> sshKey = default(List<string>))
        {
            this.SshKey = sshKey;
        }
        
        /// <summary>
        /// Gets or Sets SshKey
        /// </summary>
        [DataMember(Name="ssh_key", EmitDefaultValue=false)]
        public List<string> SshKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServerLoginUserSshKeys {\n");
            sb.Append("  SshKey: ").Append(SshKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServerLoginUserSshKeys);
        }

        /// <summary>
        /// Returns true if ServerLoginUserSshKeys instances are equal
        /// </summary>
        /// <param name="input">Instance of ServerLoginUserSshKeys to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServerLoginUserSshKeys input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SshKey == input.SshKey ||
                    this.SshKey != null &&
                    this.SshKey.SequenceEqual(input.SshKey)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SshKey != null)
                    hashCode = hashCode * 59 + this.SshKey.GetHashCode();
                return hashCode;
            }
        }
    }

}
