/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Upcloud.Client.SwaggerDateConverter;

namespace Upcloud.Model
{
    /// <summary>
    /// stop server request
    /// </summary>
    [DataContract]
    public partial class StopServerRequest :  IEquatable<StopServerRequest>
    {
        /// <summary>
        /// Type of stop operation performed on the server.
        /// </summary>
        /// <value>Type of stop operation performed on the server.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StopTypeEnum
        {
            
            /// <summary>
            /// Enum Soft for value: soft
            /// </summary>
            [EnumMember(Value = "soft")]
            Soft = 1,
            
            /// <summary>
            /// Enum Hard for value: hard
            /// </summary>
            [EnumMember(Value = "hard")]
            Hard = 2
        }

        /// <summary>
        /// Type of stop operation performed on the server.
        /// </summary>
        /// <value>Type of stop operation performed on the server.</value>
        [DataMember(Name="stop_type", EmitDefaultValue=true)]
        public StopTypeEnum? StopType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StopServerRequest" /> class.
        /// </summary>
        /// <param name="stopType">Type of stop operation performed on the server. (default to StopTypeEnum.Soft).</param>
        /// <param name="timeout">The stop timeout in seconds..</param>
        public StopServerRequest(StopTypeEnum? stopType = StopTypeEnum.Soft, decimal? timeout = default(decimal?))
        {
            // use default value if no "stopType" provided
            if (stopType == null)
            {
                this.StopType = StopTypeEnum.Soft;
            }
            else
            {
                this.StopType = stopType;
            }
            this.Timeout = timeout;
        }
        

        /// <summary>
        /// The stop timeout in seconds.
        /// </summary>
        /// <value>The stop timeout in seconds.</value>
        [DataMember(Name="timeout", EmitDefaultValue=true)]
        public decimal? Timeout { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StopServerRequest {\n");
            sb.Append("  StopType: ").Append(StopType).Append("\n");
            sb.Append("  Timeout: ").Append(Timeout).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StopServerRequest);
        }

        /// <summary>
        /// Returns true if StopServerRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of StopServerRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StopServerRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StopType == input.StopType ||
                    (this.StopType != null &&
                    this.StopType.Equals(input.StopType))
                ) && 
                (
                    this.Timeout == input.Timeout ||
                    (this.Timeout != null &&
                    this.Timeout.Equals(input.Timeout))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StopType != null)
                    hashCode = hashCode * 59 + this.StopType.GetHashCode();
                if (this.Timeout != null)
                    hashCode = hashCode * 59 + this.Timeout.GetHashCode();
                return hashCode;
            }
        }
    }

}
