/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Upcloud.Client.SwaggerDateConverter;

namespace Upcloud.Model
{
    /// <summary>
    /// StorageDevice
    /// </summary>
    [DataContract]
    public partial class StorageDevice :  IEquatable<StorageDevice>
    {
        /// <summary>
        /// Defines BootDisk
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum BootDiskEnum
        {
            
            /// <summary>
            /// Enum _0 for value: 0
            /// </summary>
            [EnumMember(Value = "0")]
            _0 = 1,
            
            /// <summary>
            /// Enum _1 for value: 1
            /// </summary>
            [EnumMember(Value = "1")]
            _1 = 2
        }

        /// <summary>
        /// Gets or Sets BootDisk
        /// </summary>
        [DataMember(Name="boot_disk", EmitDefaultValue=true)]
        public BootDiskEnum? BootDisk { get; set; }
        /// <summary>
        /// Defines Tier
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TierEnum
        {
            
            /// <summary>
            /// Enum Hdd for value: hdd
            /// </summary>
            [EnumMember(Value = "hdd")]
            Hdd = 1,
            
            /// <summary>
            /// Enum Maxiops for value: maxiops
            /// </summary>
            [EnumMember(Value = "maxiops")]
            Maxiops = 2
        }

        /// <summary>
        /// Gets or Sets Tier
        /// </summary>
        [DataMember(Name="tier", EmitDefaultValue=true)]
        public TierEnum? Tier { get; set; }
        /// <summary>
        /// Defines Action
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            
            /// <summary>
            /// Enum Create for value: create
            /// </summary>
            [EnumMember(Value = "create")]
            Create = 1,
            
            /// <summary>
            /// Enum Clone for value: clone
            /// </summary>
            [EnumMember(Value = "clone")]
            Clone = 2,
            
            /// <summary>
            /// Enum Attach for value: attach
            /// </summary>
            [EnumMember(Value = "attach")]
            Attach = 3
        }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="action", EmitDefaultValue=true)]
        public ActionEnum? Action { get; set; }
        /// <summary>
        /// Defines PartOfPlan
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PartOfPlanEnum
        {
            
            /// <summary>
            /// Enum Yes for value: yes
            /// </summary>
            [EnumMember(Value = "yes")]
            Yes = 1,
            
            /// <summary>
            /// Enum No for value: no
            /// </summary>
            [EnumMember(Value = "no")]
            No = 2
        }

        /// <summary>
        /// Gets or Sets PartOfPlan
        /// </summary>
        [DataMember(Name="part_of_plan", EmitDefaultValue=true)]
        public PartOfPlanEnum? PartOfPlan { get; set; }
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum Disk for value: disk
            /// </summary>
            [EnumMember(Value = "disk")]
            Disk = 1,
            
            /// <summary>
            /// Enum Cdrom for value: cdrom
            /// </summary>
            [EnumMember(Value = "cdrom")]
            Cdrom = 2
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=true)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageDevice" /> class.
        /// </summary>
        /// <param name="title">title.</param>
        /// <param name="bootDisk">bootDisk (default to BootDiskEnum._0).</param>
        /// <param name="size">The size of the storage device in gigabytes..</param>
        /// <param name="tier">tier (default to TierEnum.Hdd).</param>
        /// <param name="action">action.</param>
        /// <param name="address">address.</param>
        /// <param name="partOfPlan">partOfPlan.</param>
        /// <param name="storage">storage.</param>
        /// <param name="storageSize">storageSize.</param>
        /// <param name="storageTitle">storageTitle.</param>
        /// <param name="type">type (default to TypeEnum.Disk).</param>
        public StorageDevice(string title = default(string), BootDiskEnum? bootDisk = BootDiskEnum._0, decimal? size = default(decimal?), TierEnum? tier = TierEnum.Hdd, ActionEnum? action = default(ActionEnum?), string address = default(string), PartOfPlanEnum? partOfPlan = default(PartOfPlanEnum?), string storage = default(string), decimal? storageSize = default(decimal?), string storageTitle = default(string), TypeEnum? type = TypeEnum.Disk)
        {
            this.Title = title;
            // use default value if no "bootDisk" provided
            if (bootDisk == null)
            {
                this.BootDisk = BootDiskEnum._0;
            }
            else
            {
                this.BootDisk = bootDisk;
            }
            this.Size = size;
            // use default value if no "tier" provided
            if (tier == null)
            {
                this.Tier = TierEnum.Hdd;
            }
            else
            {
                this.Tier = tier;
            }
            this.Action = action;
            this.Address = address;
            this.PartOfPlan = partOfPlan;
            this.Storage = storage;
            this.StorageSize = storageSize;
            this.StorageTitle = storageTitle;
            // use default value if no "type" provided
            if (type == null)
            {
                this.Type = TypeEnum.Disk;
            }
            else
            {
                this.Type = type;
            }
        }
        
        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title", EmitDefaultValue=true)]
        public string Title { get; set; }


        /// <summary>
        /// The size of the storage device in gigabytes.
        /// </summary>
        /// <value>The size of the storage device in gigabytes.</value>
        [DataMember(Name="size", EmitDefaultValue=true)]
        public decimal? Size { get; set; }



        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address", EmitDefaultValue=true)]
        public string Address { get; set; }


        /// <summary>
        /// Gets or Sets Storage
        /// </summary>
        [DataMember(Name="storage", EmitDefaultValue=true)]
        public string Storage { get; set; }

        /// <summary>
        /// Gets or Sets StorageSize
        /// </summary>
        [DataMember(Name="storage_size", EmitDefaultValue=true)]
        public decimal? StorageSize { get; set; }

        /// <summary>
        /// Gets or Sets StorageTitle
        /// </summary>
        [DataMember(Name="storage_title", EmitDefaultValue=true)]
        public string StorageTitle { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StorageDevice {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  BootDisk: ").Append(BootDisk).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  PartOfPlan: ").Append(PartOfPlan).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  StorageSize: ").Append(StorageSize).Append("\n");
            sb.Append("  StorageTitle: ").Append(StorageTitle).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StorageDevice);
        }

        /// <summary>
        /// Returns true if StorageDevice instances are equal
        /// </summary>
        /// <param name="input">Instance of StorageDevice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StorageDevice input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.BootDisk == input.BootDisk ||
                    (this.BootDisk != null &&
                    this.BootDisk.Equals(input.BootDisk))
                ) && 
                (
                    this.Size == input.Size ||
                    (this.Size != null &&
                    this.Size.Equals(input.Size))
                ) && 
                (
                    this.Tier == input.Tier ||
                    (this.Tier != null &&
                    this.Tier.Equals(input.Tier))
                ) && 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.PartOfPlan == input.PartOfPlan ||
                    (this.PartOfPlan != null &&
                    this.PartOfPlan.Equals(input.PartOfPlan))
                ) && 
                (
                    this.Storage == input.Storage ||
                    (this.Storage != null &&
                    this.Storage.Equals(input.Storage))
                ) && 
                (
                    this.StorageSize == input.StorageSize ||
                    (this.StorageSize != null &&
                    this.StorageSize.Equals(input.StorageSize))
                ) && 
                (
                    this.StorageTitle == input.StorageTitle ||
                    (this.StorageTitle != null &&
                    this.StorageTitle.Equals(input.StorageTitle))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.BootDisk != null)
                    hashCode = hashCode * 59 + this.BootDisk.GetHashCode();
                if (this.Size != null)
                    hashCode = hashCode * 59 + this.Size.GetHashCode();
                if (this.Tier != null)
                    hashCode = hashCode * 59 + this.Tier.GetHashCode();
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.PartOfPlan != null)
                    hashCode = hashCode * 59 + this.PartOfPlan.GetHashCode();
                if (this.Storage != null)
                    hashCode = hashCode * 59 + this.Storage.GetHashCode();
                if (this.StorageSize != null)
                    hashCode = hashCode * 59 + this.StorageSize.GetHashCode();
                if (this.StorageTitle != null)
                    hashCode = hashCode * 59 + this.StorageTitle.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }
    }

}
